/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dental_clinic_management_system;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class AppointmentsForm extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentsForm
     */
    public AppointmentsForm() {
        initComponents();
        GetPatient();
        GetTreatment();
        DisplayAppoitments();
        A_ID_Count();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_appointment = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_A_edit = new javax.swing.JButton();
        btn_A_save = new javax.swing.JButton();
        btn_A_delete = new javax.swing.JButton();
        btn_A_clear = new javax.swing.JButton();
        Dc_Date = new com.toedter.calendar.JDateChooser();
        cmb_treatment = new javax.swing.JComboBox<>();
        Dc_time = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cmb_patient = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        patient = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        appoinments = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        prescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Appoinments");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Time");

        tbl_appointment.setBackground(new java.awt.Color(255, 255, 153));
        tbl_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patient_Name", "Date", "Time", "Treatment"
            }
        ));
        tbl_appointment.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_appointment.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tbl_appointment.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_appointmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_appointment);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Appoinment List");

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText(" X");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        btn_A_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_A_edit.setText("Edit");
        btn_A_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_A_editMouseClicked(evt);
            }
        });

        btn_A_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_A_save.setText("Save");
        btn_A_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_A_saveMouseClicked(evt);
            }
        });

        btn_A_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_A_delete.setText("Delete");
        btn_A_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_A_deleteMouseClicked(evt);
            }
        });

        btn_A_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_A_clear.setText("Clear");
        btn_A_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_A_clearMouseClicked(evt);
            }
        });

        cmb_treatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", " " }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Treatment");

        cmb_patient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dc_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmb_treatment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Dc_time, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(cmb_patient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_A_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_A_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_A_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_A_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_A_save)
                                        .addGap(9, 9, 9))
                                    .addComponent(Dc_Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_A_edit)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(cmb_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(Dc_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_A_delete))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_A_clear)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        patient.setBackground(new java.awt.Color(51, 51, 51));
        patient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patient.setText("Patients");
        patient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Treatments");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        appoinments.setBackground(new java.awt.Color(51, 51, 51));
        appoinments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appoinments.setText("Dashboard");
        appoinments.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        appoinments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appoinmentsMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Dental Clinic");

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        prescription.setBackground(new java.awt.Color(51, 51, 51));
        prescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prescription.setText("Prescription");
        prescription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        prescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(patient))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(appoinments)
                                .addComponent(prescription)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(99, 99, 99)
                .addComponent(patient)
                .addGap(35, 35, 35)
                .addComponent(prescription)
                .addGap(38, 38, 38)
                .addComponent(appoinments)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_appointmentMouseClicked
        DefaultTableModel Model=(DefaultTableModel)tbl_appointment.getModel();
        int Myindex=tbl_appointment.getSelectedRow();
        
        key=Integer.valueOf(Model.getValueAt(Myindex, 0).toString());
        
       
        cmb_patient.setSelectedItem(Model.getValueAt(Myindex, 1).toString());
        cmb_treatment.setSelectedItem(Model.getValueAt(Myindex, 4).toString());     

    }//GEN-LAST:event_tbl_appointmentMouseClicked

    private void btn_A_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_A_editMouseClicked
       if(key==0)
       {
           
           JOptionPane.showMessageDialog(this, "Select the Appoinment");
       }
       else
       {
        
        try{
           
           
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
           String Query="Update appointment_details set P_Name='"+cmb_patient.getSelectedItem().toString()+"'"+",Date='"+Dc_Date.getDate().toString()+"'"+",Time='"+Dc_time.getDate().toString()+"'"+",Treatments='"+cmb_patient.getSelectedItem().toString()+"' Where App_ID="+key;
           Statement up=conn.createStatement();
           up.execute(Query);
           JOptionPane.showMessageDialog(this, "Treatment Updated Successfully");
           conn.close();
           tblModel.setRowCount(0);
           DisplayAppoitments();
           Clear();
           
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }
       }
        
    }//GEN-LAST:event_btn_A_editMouseClicked

    private void btn_A_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_A_saveMouseClicked
       if(cmb_patient.getSelectedIndex() == -1 || cmb_treatment.getSelectedIndex()== -1 )
       {
           
           JOptionPane.showMessageDialog(this, "Missing Information");
       }
       else
       {
        
        try{
           
           A_ID_Count();
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
           String sql = "insert into Appointment_details values (?,?,?,?,?)";
           PreparedStatement add= conn.prepareStatement(sql);
           
           add.setInt(1, appoinment_ID);           
           add.setString(2, cmb_patient.getSelectedItem().toString());
           add.setString(3, Dc_Date.getDate().toString());
           add.setString(4, String.valueOf(Dc_time.getDate().getTime()));
           add.setString(5, cmb_treatment.getSelectedItem().toString());
           
           int row=add.executeUpdate();
           JOptionPane.showMessageDialog(this, "Appointment Insereted Successfully");
           conn.close();
           tblModel.setRowCount(0);
          DisplayAppoitments();
          Clear();
          
           
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }
       }       
    }//GEN-LAST:event_btn_A_saveMouseClicked

    private void btn_A_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_A_deleteMouseClicked
     if(key==0)
        {

            JOptionPane.showMessageDialog(this, "Select the Appointment");
        }
        else
        {

            try{

                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
                String Q="Delete from Appointment_details where App_ID="+key;
                Statement up=conn.createStatement();
                up.execute(Q);
                JOptionPane.showMessageDialog(this, "Appoinment Deleted Successfully");
                conn.close();
                tblModel.setRowCount(0);
                DisplayAppoitments();
                Clear();

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_A_deleteMouseClicked

    private void btn_A_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_A_clearMouseClicked
        Clear();
    }//GEN-LAST:event_btn_A_clearMouseClicked

    private void patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseClicked
        PatientsForm t1=new PatientsForm();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TreatmentForm t1=new TreatmentForm();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void appoinmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appoinmentsMouseClicked
        Dashbord a1=new Dashbord();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appoinmentsMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LoginForm l1=new LoginForm();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void prescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionMouseClicked
        PrescriptionForm p1=new PrescriptionForm();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prescriptionMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    Connection conn=null;
    ResultSet rs=null,rs1=null;
    Statement st=null,st1=null;
    int key;
    int appoinment_ID=0;
    DefaultTableModel tblModel;
    
    private void GetPatient()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
            st=(Statement) conn.createStatement();
            String query="Select * from patient_details";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                String pName=rs.getString("P_Name");
                cmb_patient.addItem(pName);
               
            }
            
        } catch (Exception e) {
        }
    }
    
    private void GetTreatment()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
            st=(Statement) conn.createStatement();
            String query="Select * from treatment_details";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                String tName=rs.getString("Treatment_Name");
                cmb_treatment.addItem(tName);
            }
            
        } catch (Exception e) {
        }
    }
    
    private void DisplayAppoitments()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
            st=(Statement) conn.createStatement();
            rs=st.executeQuery("Select * from appointment_details");
            
            
            while(rs.next())
            {
                String ID=String.valueOf(rs.getString("App_ID"));
                String patient_Name=String.valueOf(rs.getString("P_Name"));
                String Date=String.valueOf(rs.getString("Date"));
                String Time=String.valueOf(rs.getString("Time"));
                String Treatment=String.valueOf(rs.getString("Treatments"));
                
                String tbData[]={ID,patient_Name,Date,Time,Treatment};
                tblModel=(DefaultTableModel)tbl_appointment.getModel();
                
         
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {
        }
    }
    
    private void A_ID_Count()
    {
        try {
            st1=conn.createStatement();
            rs1=st1.executeQuery("select Max(App_ID) from appointment_details");
            rs1.next();
            appoinment_ID= rs1.getInt(1)+1;
        } catch (Exception e) {
        }
    }
    private void Clear()
    {
        cmb_patient.setSelectedIndex(0);
        cmb_treatment.setSelectedIndex(0);
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Dc_Date;
    private com.toedter.calendar.JDateChooser Dc_time;
    private javax.swing.JLabel appoinments;
    private javax.swing.JButton btn_A_clear;
    private javax.swing.JButton btn_A_delete;
    private javax.swing.JButton btn_A_edit;
    private javax.swing.JButton btn_A_save;
    private javax.swing.JComboBox<String> cmb_patient;
    private javax.swing.JComboBox<String> cmb_treatment;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel prescription;
    private javax.swing.JTable tbl_appointment;
    // End of variables declaration//GEN-END:variables
}
