/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dental_clinic_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PrescriptionForm extends javax.swing.JFrame {

    /**
     * Creates new form PrescriptionForm
     */
    public PrescriptionForm() {
        initComponents();
        GetPatient();
        DisplayPrescription();
        Pr_ID_Count();
    }

    
    
    Connection conn=null;
    ResultSet rs=null,rs1=null;
    Statement st=null,st1=null;
    int key;
    int prescription_ID=0;
    DefaultTableModel tblModel;
    
    private void Clear()
    {
        txt_pr_treatment.setText("");
        txt_pr_cost.setText("");
        txt_pr_quentity.setText("");
        txt_pr_medicine.setText("");
        cmb_pr_patient.setSelectedIndex(0);
        
    }
    private void DisplayPrescription()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
            st=(Statement) conn.createStatement();
            rs=st.executeQuery("Select * from prescription_details");
            
            
            while(rs.next())
            {
                String ID=String.valueOf(rs.getString("Pres_ID"));
                String Treatment_Name=String.valueOf(rs.getString("Treatment"));
                String Cost=String.valueOf(rs.getString("Cost"));
                String P_Name=String.valueOf(rs.getString("P_Name"));
                String Quentity=String.valueOf(rs.getString("Quentity"));
                String Medicine=String.valueOf(rs.getString("Medicine"));
                
                String tbData[]={ID,Treatment_Name,Cost,P_Name,Quentity,Medicine};
                tblModel=(DefaultTableModel)tbl_prescription.getModel();
                
         
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {
        }
    }
    
    private void Pr_ID_Count()
    {
        try {
            st1=conn.createStatement();
            rs1=st1.executeQuery("select Max(Pres_ID) from prescription_details");
            rs1.next();
            prescription_ID= rs1.getInt(1)+1;
        } catch (Exception e) {
        }
    }
    private void GetPatient()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
            st=(Statement) conn.createStatement();
            String query="Select * from patient_details";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                String pName=rs.getString("P_Name");
                cmb_pr_patient.addItem(pName);
               
            }
            
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_pr_quentity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prescription = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cmb_pr_patient = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btn_pr_edit = new javax.swing.JButton();
        btn_pr_save = new javax.swing.JButton();
        btn_p_delete = new javax.swing.JButton();
        txt_pr_cost = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_pr_medicine = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_pr_treatment = new javax.swing.JTextField();
        btn_pr_clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        patient2 = new javax.swing.JLabel();
        prescription2 = new javax.swing.JLabel();
        appoinments2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logout2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cost");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Patient");

        txt_pr_quentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pr_quentityActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quentity");

        tbl_prescription.setBackground(new java.awt.Color(255, 255, 102));
        tbl_prescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Treatments", "Cost", "PatientName", "Quentity", "Medicines"
            }
        ));
        tbl_prescription.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tbl_prescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prescriptionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prescription);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Prescription List");

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText(" X");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        btn_pr_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_pr_edit.setText("Edit");
        btn_pr_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pr_editMouseClicked(evt);
            }
        });

        btn_pr_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_pr_save.setText("Save");
        btn_pr_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pr_saveMouseClicked(evt);
            }
        });
        btn_pr_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pr_saveActionPerformed(evt);
            }
        });

        btn_p_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_p_delete.setText("Delete");
        btn_p_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_p_deleteMouseClicked(evt);
            }
        });

        txt_pr_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pr_costActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Medicines");

        txt_pr_medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pr_medicineActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Treatment");

        txt_pr_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pr_treatmentActionPerformed(evt);
            }
        });

        btn_pr_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_pr_clear.setText("Clear");
        btn_pr_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pr_clearMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_pr_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_pr_quentity, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(27, 27, 27)
                                .addComponent(txt_pr_medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_pr_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pr_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_p_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(btn_pr_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_pr_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pr_save, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_pr_treatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_pr_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmb_pr_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_pr_quentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_pr_medicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(23, 23, 23)
                        .addComponent(btn_pr_save)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pr_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_p_delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pr_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Dental Clinic");

        patient2.setBackground(new java.awt.Color(51, 51, 51));
        patient2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patient2.setText("Appoinment");
        patient2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        patient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient2MouseClicked(evt);
            }
        });

        prescription2.setBackground(new java.awt.Color(51, 51, 51));
        prescription2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prescription2.setText("patient");
        prescription2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        prescription2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescription2MouseClicked(evt);
            }
        });

        appoinments2.setBackground(new java.awt.Color(51, 51, 51));
        appoinments2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appoinments2.setText("Dashboard");
        appoinments2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        appoinments2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appoinments2MouseClicked(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Treatments");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), null, null));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        logout2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout2.setForeground(new java.awt.Color(255, 0, 0));
        logout2.setText("LOGOUT");
        logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addComponent(appoinments2)
                        .addComponent(prescription2)
                        .addComponent(patient2)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(93, 93, 93)
                .addComponent(patient2)
                .addGap(41, 41, 41)
                .addComponent(prescription2)
                .addGap(38, 38, 38)
                .addComponent(appoinments2)
                .addGap(42, 42, 42)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pr_quentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pr_quentityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pr_quentityActionPerformed

    private void txt_pr_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pr_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pr_costActionPerformed

    private void txt_pr_medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pr_medicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pr_medicineActionPerformed

    private void txt_pr_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pr_treatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pr_treatmentActionPerformed

    private void btn_pr_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pr_clearMouseClicked
        Clear();
    }//GEN-LAST:event_btn_pr_clearMouseClicked

    private void btn_pr_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pr_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pr_saveActionPerformed

    private void btn_pr_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pr_saveMouseClicked
        if(txt_pr_cost.getText().isEmpty() || cmb_pr_patient.getSelectedIndex() == -1 ||txt_pr_medicine.getText().isEmpty() || txt_pr_quentity.getText().isEmpty() || txt_pr_treatment.getText().isEmpty())
       {
           
           JOptionPane.showMessageDialog(this, "Missing Information");
       }
       else
       {
        
        try{
           
           Pr_ID_Count();
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
           String sql = "insert into prescription_details values (?,?,?,?,?,?)";
           PreparedStatement add= conn.prepareStatement(sql);
           
           add.setInt(1, prescription_ID);
           add.setString(2, txt_pr_treatment.getText());
           add.setString(3, txt_pr_cost.getText());
           add.setString(4, cmb_pr_patient.getSelectedItem().toString());
           add.setString(5, txt_pr_quentity.getText());
           add.setString(6, txt_pr_treatment.getText());
           
           int row=add.executeUpdate();
           JOptionPane.showMessageDialog(this, "Prescription Insereted Successfully");
           conn.close();
           tblModel.setRowCount(0);
          DisplayPrescription();
          Clear();
          
           
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }
       }
    }//GEN-LAST:event_btn_pr_saveMouseClicked

    private void btn_pr_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pr_editMouseClicked
        if(key==0)
       {
           
           JOptionPane.showMessageDialog(this, "Select the prescription ID");
       }
       else
       {
        
        try{
           
           
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
           String Query="Update prescription_details set Treatment='"+txt_pr_treatment.getText()+"'"+",Cost='"+txt_pr_cost.getText()+"'"+",P_Name='"+cmb_pr_patient.getSelectedItem().toString()+"'"+",Quentity='"+txt_pr_quentity.getText()+"'"+",Medicine='"+txt_pr_medicine.getText()+"' Where Pres_ID="+key;
           Statement up=conn.createStatement();
           up.execute(Query);
           JOptionPane.showMessageDialog(this, "Prescription Updated Successfully");
           conn.close();
           tblModel.setRowCount(0);
           DisplayPrescription();
           Clear();
           
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }
       }
    }//GEN-LAST:event_btn_pr_editMouseClicked

    private void btn_p_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_p_deleteMouseClicked
        if(key==0)
        {

            JOptionPane.showMessageDialog(this, "Select the Prescription ID");
        }
        else
        {

            try{

                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dental_management","root","");
                String Q="Delete from prescription_details where Pres_ID="+key;
                Statement up=conn.createStatement();
                up.execute(Q);
                JOptionPane.showMessageDialog(this, "Prescription Deleted Successfully");
                conn.close();
                tblModel.setRowCount(0);
                DisplayPrescription();
                Clear();

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_p_deleteMouseClicked

    private void tbl_prescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prescriptionMouseClicked
        DefaultTableModel Model=(DefaultTableModel)tbl_prescription.getModel();
        int Myindex=tbl_prescription.getSelectedRow();
        
        key=Integer.valueOf(Model.getValueAt(Myindex, 0).toString());
        
       
        txt_pr_treatment.setText(Model.getValueAt(Myindex, 1).toString());
        txt_pr_cost.setText(Model.getValueAt(Myindex, 2).toString());
        cmb_pr_patient.setSelectedItem(Model.getValueAt(Myindex, 3).toString());
        txt_pr_quentity.setText(Model.getValueAt(Myindex, 4).toString());
        txt_pr_medicine.setText(Model.getValueAt(Myindex, 5).toString());
    }//GEN-LAST:event_tbl_prescriptionMouseClicked

    private void patient2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient2MouseClicked
        AppointmentsForm t1=new AppointmentsForm();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patient2MouseClicked

    private void prescription2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescription2MouseClicked
        PatientsForm p1=new PatientsForm();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prescription2MouseClicked

    private void appoinments2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appoinments2MouseClicked
        Dashbord a1=new Dashbord();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appoinments2MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        TreatmentForm t1=new TreatmentForm();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MouseClicked
        LoginForm l1=new LoginForm();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout2MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrescriptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrescriptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrescriptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrescriptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrescriptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appoinments2;
    private javax.swing.JButton btn_p_delete;
    private javax.swing.JButton btn_pr_clear;
    private javax.swing.JButton btn_pr_edit;
    private javax.swing.JButton btn_pr_save;
    private javax.swing.JComboBox<String> cmb_pr_patient;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout2;
    private javax.swing.JLabel patient2;
    private javax.swing.JLabel prescription2;
    private javax.swing.JTable tbl_prescription;
    private javax.swing.JTextField txt_pr_cost;
    private javax.swing.JTextField txt_pr_medicine;
    private javax.swing.JTextField txt_pr_quentity;
    private javax.swing.JTextField txt_pr_treatment;
    // End of variables declaration//GEN-END:variables
}
